export const games = [
    {
      id: "1",
      title: "God of War",
      genre: ["RPG", "Action", "Adventure"],
      image: "/images/GodOfWar.jpg",
      vertical_image: "/images/GodofWar.jpg",
      price: "$249",
      description:
        "God of War is a mythology-based action-adventure video game franchise. Created by David Jaffe at Sony's Santa Monica Studio.",
    },
    {
      id: "2",
      title: "Black Myth Wukong",
      genre: ["RPG", "Action", "Combat"],
      image: "/images/BlackMythWukong.jpg",
      vertical_image: "/images/black-myth-wukong-vertical.jpg",
      price: "$219",
      description:
        "Black Myth: Wukong is an upcoming action-adventure video game developed by Chinese indie developer Game Science.",
    },
    {
      id: "3",
      title: "Elden Ring",
      genre: ["RPG", "Fantasy", "Action"],
      image: "/images/EldenRing.jpg",
      vertical_image: "/images/elden-ring-vertical.jpg",
      banner: "/images/GodofWar.jpg",
      price: "$199",
      description:
        "Elden Ring is an upcoming action role-playing game developed by FromSoftware and published by Bandai Namco Entertainment.",
    },
    {
      id: "4",
      title: "Cyberpunk 2077",
      genre: ["Open World", "Nudity", "RPG"],
      image: "/images/Cyberpunk2077.jpg",
      vertical_image: "/images/cyberpunk-vertical.jpg",
      banner: "/images/GodofWar.jpg",
      price: "$219",
      description: "Cyberpunk 2077 is an action role-playing video game developed and published by CD Projekt.",
    },
    {
      id: "5",
      title: "Sekiro",
      genre: ["Action", "Single-Player", "Souls-Like"],
      image: "/images/Sekiro.jpg",
      vertical_image: "/images/sekiro-vertical.jpg",
      price: "$142",
      description: "Sekiro: Shadows Die Twice is an action-adventure game played from a third-person view.",
    },
    {
      id: "6",
      title: "Lethal Company",
      genre: ["Horror", "Online Co-Op", "First-Person"],
      image: "/images/LethalCompany.jpg",
      vertical_image: "/images/lethal-company-vertical.jpg",
      price: "$26",
      description: "Lethal Company is a first-person shooter video game developed by A4 Games.",
    },
    {
      id: "7",
      title: "Monster Hunter Rise",
      genre: ["Action", "Hunting", "RPG"],
      image: "/images/MonsterHunterRise.png",
      vertical_image: "/images/monster-hunter-rise-vertical.jpg",
      price: "$163",
      description: "Monster Hunter Rise is an action role-playing game developed and published by Capcom.",
    },
    {
      id: "8",
      title: "GTA V",
      genre: ["Open-World", "Action", "Crime"],
      image: "/images/GTAV.jpg",
      vertical_image: "/images/gtav-vertical.jpg",
      price: "$158",
      description:
        "Grand Theft Auto V is a 2013 action-adventure game developed by Rockstar North and published by Rockstar Games.",
    },
    {
      id: "9",
      title: "PayDay 3",
      genre: ["FPS", "Heist", "Multiplayer"],
      image: "/images/PayDay3.jpg",
      vertical_image: "/images/payday3-vertical.jpg",
      price: "$125",
      description: "PayDay 3 is an upcoming cooperative first-person shooter video game developed by Overkill Software.",
    },
    {
      id: "10",
      title: "RDR2",
      genre: ["Open-World", "Story Rich", "Adventure"],
      image: "/images/RDR2.jpg",
      vertical_image: "/images/rdr2-vertical.jpg",
      price: "$249",
      description: "Red Dead Redemption 2 is a 2018 action-adventure game developed and published by Rockstar Games.",
    },
  ];
  