export const games = [
    {
      id: "1",
      title: "God of War",
      genre: ["RPG", "Action", "Adventure"],
      image: "/images/GodOfWar.jpg",
      vertical_image: "/images/GodofWar.jpg",
      price: "$249",
      description:
        "God of War 4 (2018) follows Kratos, now living in a world inspired by Norse mythology, as he embarks on a journey with his son, Atreus, to fulfill his late wife's final wish. The game blends intense combat with a deeply emotional narrative, focusing on their evolving father-son relationship while battling gods and monsters.",
    },
    {
      id: "2",
      title: "Black Myth Wukong",
      genre: ["RPG", "Action", "Combat"],
      image: "/images/BlackMythWukong.jpg",
      vertical_image: "/images/black-myth-wukong-vertical.jpg",
      price: "$219",
      description:
        "Wukong is an action RPG set in a world inspired by the Chinese classic Journey to the West, where players control the legendary Monkey King as he battles mythological creatures. The game features stunning visuals, fluid combat mechanics, and a rich narrative, blending folklore with fast-paced gameplay and immersive exploration.",
    },
    {
      id: "3",
      title: "Elden Ring",
      genre: ["RPG", "Fantasy", "Action"],
      image: "/images/EldenRing.jpg",
      vertical_image: "/images/elden-ring-vertical.jpg",
      banner: "/images/GodofWar.jpg",
      price: "$199",
      description:
        "Elden Ring is an open-world action RPG created by FromSoftware and George R.R. Martin, set in the vast Lands Between, where players must gather fragments of the Elden Ring to become the Elden Lord. The game offers deep lore, challenging combat, and exploration through a dark, fantastical world filled with secrets, powerful enemies, and sprawling landscapes.",
    },
    {
      id: "4",
      title: "Cyberpunk 2077",
      genre: ["Open World", "Nudity", "RPG"],
      image: "/images/Cyberpunk2077.jpg",
      vertical_image: "/images/cyberpunk-vertical.jpg",
      banner: "/images/GodofWar.jpg",
      price: "$219",
      description: "Cyberpunk 2077 is a futuristic open-world RPG set in the dystopian Night City, where players assume the role of V, a mercenary navigating a world of high-tech cybernetics, crime, and corporate warfare. The game features a rich narrative with branching choices, immersive world-building, and fast-paced combat, blending RPG elements with first-person action.",
    },
    {
      id: "5",
      title: "Sekiro",
      genre: ["Action", "Single-Player", "Souls-Like"],
      image: "/images/Sekiro.jpg",
      vertical_image: "/images/sekiro-vertical.jpg",
      price: "$142",
      description: "Shadows Die Twice is an action-adventure game set in a reimagined late 1500s Japan, where players control a shinobi named Wolf on a quest to rescue his kidnapped lord and seek revenge. The game features intense sword combat, stealth, and a unique resurrection mechanic, offering brutal challenges with a focus on precise timing and strategy.",
    },
    {
      id: "6",
      title: "Lethal Company",
      genre: ["Horror", "Online Co-Op", "First-Person"],
      image: "/images/LethalCompany.jpg",
      vertical_image: "/images/lethal-company-vertical.jpg",
      price: "$26",
      description: "Lethal Company is a multiplayer horror game where players must explore haunted industrial sites while scavenging for valuable items, all while avoiding terrifying creatures that lurk in the darkness. The game emphasizes teamwork, with a blend of tense atmosphere, survival elements, and cooperative problem-solving to escape alive.",
    },
    {
      id: "7",
      title: "Monster Hunter Rise",
      genre: ["Action", "Hunting", "RPG"],
      image: "/images/MonsterHunterRise.png",
      vertical_image: "/images/monster-hunter-rise-vertical.jpg",
      price: "$163",
      description: "Monster Hunter Rise is an action RPG where players take on the role of a hunter tasked with slaying or capturing large, powerful monsters in the vibrant, open world of Kamura Village. The game features fast-paced combat, a variety of weapons, and new mobility mechanics like the Wirebug, allowing for dynamic exploration and thrilling battles against towering creatures.",
    },
    {
      id: "8",
      title: "GTA V",
      genre: ["Open-World", "Action", "Crime"],
      image: "/images/GTAV.jpg",
      vertical_image: "/images/gtav-vertical.jpg",
      price: "$158",
      description:
        "Grand Theft Auto V is an open-world action-adventure game set in the sprawling city of Los Santos, where players control three unique characters—Michael, Franklin, and Trevor—who navigate a world of crime, heists, and corruption. The game offers a rich narrative, dynamic missions, and a vast sandbox environment filled with activities, blending story-driven gameplay with chaotic freedom.",
    },
    {
      id: "9",
      title: "PayDay 3",
      genre: ["FPS", "Heist", "Multiplayer"],
      image: "/images/PayDay3.jpg",
      vertical_image: "/images/payday3-vertical.jpg",
      price: "$125",
      description: "Payday 3 is a cooperative first-person shooter that puts players in the shoes of skilled criminals planning and executing heists across various high-stakes scenarios. Building on its predecessor, the game features enhanced graphics, deeper character customization, and a range of new heist mechanics, encouraging teamwork and strategic planning to achieve lucrative goals while evading law enforcement.",
    },
    {
      id: "10",
      title: "RDR2",
      genre: ["Open-World", "Story Rich", "Adventure"],
      image: "/images/RDR2.jpg",
      vertical_image: "/images/rdr2-vertical.jpg",
      price: "$249",
      description: "Red Dead Redemption 2 is an open-world action-adventure game set in the late 1800s that follows Arthur Morgan, a member of the Van der Linde gang, as they navigate the challenges of outlaw life while facing law enforcement and rival gangs. With its richly detailed world, immersive storytelling, and deep character development, the game explores themes of loyalty, morality, and the fading of the Wild West.",
    },
  ];
  